/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.heitian.ssm.model;

import java.util.Date;


/**
 * A data object class directly models database table <tt>tb_login</tt>.
 * 
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tb_login.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
public class TbLoginDO  extends Entity {
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========
	/**
	 * 电话
	*/
	protected String phone;
	/**
	 * 密码
	*/
	protected String password;
	/**
	 * 最后登录时间
	*/
	protected Date lastLoginTime;
	/**
	 * 最后登录地址
	*/
	protected String lastLoginAddress;
	/**
	 * 登录次数
	*/
	protected Long loginNumber;

	//========== getters and setters ==========
    /**
     * 返回 电话
     */
	public String getPhone() {
		return phone;
	}

	/**
	 * 设置 电话
     */
	public void setPhone(String phone) {
		this.phone = phone;
    }
    /**
     * 返回 密码
     */
	public String getPassword() {
		return password;
	}

	/**
	 * 设置 密码
     */
	public void setPassword(String password) {
		this.password = password;
    }
    /**
     * 返回 最后登录时间
     */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * 设置 最后登录时间
     */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
    }
    /**
     * 返回 最后登录地址
     */
	public String getLastLoginAddress() {
		return lastLoginAddress;
	}

	/**
	 * 设置 最后登录地址
     */
	public void setLastLoginAddress(String lastLoginAddress) {
		this.lastLoginAddress = lastLoginAddress;
    }
    /**
     * 返回 登录次数
     */
	public Long getLoginNumber() {
		return loginNumber;
	}

	/**
	 * 设置 登录次数
     */
	public void setLoginNumber(Long loginNumber) {
		this.loginNumber = loginNumber;
    }

}
