/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.heitian.ssm.model;

import java.util.Date;


/**
 * A data object class directly models database table <tt>tb_log</tt>.
 * 
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tb_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
public class TbLogDO  extends Entity {
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========
	/**
	 * 内容
	*/
	protected String content;
	/**
	 * 日志编号，逗号分隔
	*/
	protected String logNumber;
	/**
	 * 审核人
	*/
	protected Long checkUser;
	/**
	 * 审核人名称
	*/
	protected String checkUsername;
	/**
	 * 审核时间
	*/
	protected Date checkTime;
	/**
	 * 审核通过与否-0：未通过，1：通过了
	*/
	protected Long state;

	//========== getters and setters ==========
    /**
     * 返回 内容
     */
	public String getContent() {
		return content;
	}

	/**
	 * 设置 内容
     */
	public void setContent(String content) {
		this.content = content;
    }
    /**
     * 返回 日志编号，逗号分隔
     */
	public String getLogNumber() {
		return logNumber;
	}

	/**
	 * 设置 日志编号，逗号分隔
     */
	public void setLogNumber(String logNumber) {
		this.logNumber = logNumber;
    }
    /**
     * 返回 审核人
     */
	public Long getCheckUser() {
		return checkUser;
	}

	/**
	 * 设置 审核人
     */
	public void setCheckUser(Long checkUser) {
		this.checkUser = checkUser;
    }
    /**
     * 返回 审核人名称
     */
	public String getCheckUsername() {
		return checkUsername;
	}

	/**
	 * 设置 审核人名称
     */
	public void setCheckUsername(String checkUsername) {
		this.checkUsername = checkUsername;
    }
    /**
     * 返回 审核时间
     */
	public Date getCheckTime() {
		return checkTime;
	}

	/**
	 * 设置 审核时间
     */
	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
    }
    /**
     * 返回 审核通过与否-0：未通过，1：通过了
     */
	public Long getState() {
		return state;
	}

	/**
	 * 设置 审核通过与否-0：未通过，1：通过了
     */
	public void setState(Long state) {
		this.state = state;
    }

}
