/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.heitian.ssm.model;


/**
 * A data object class directly models database table <tt>tb_notice</tt>.
 * 
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tb_notice.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
public class TbNoticeDO  extends Entity {
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========
	/**
	 * 内容
	*/
	protected String content;
	/**
	 * 查看次数
	*/
	protected Long lookNumber;

	protected Long category;

	//========== getters and setters ==========
    /**
     * 返回 内容
     */
	public String getContent() {
		return content;
	}

	/**
	 * 设置 内容
     */
	public void setContent(String content) {
		this.content = content;
    }
    /**
     * 返回 查看次数
     */
	public Long getLookNumber() {
		return lookNumber;
	}

	/**
	 * 设置 查看次数
     */
	public void setLookNumber(Long lookNumber) {
		this.lookNumber = lookNumber;
    }

	public Long getCategory() {
		return category;
	}

	public void setCategory(Long category) {
		this.category = category;
	}
}
