/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.heitian.ssm.model;


/**
 * A data object class directly models database table <tt>tb_role</tt>.
 * 
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tb_role.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
public class TbRoleDO  extends Entity {
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========
	/**
	 * 职能
	*/
	protected String func;
	/**
	 * 角色的级别0-1-2-3....
	*/
	protected Long level;
//	/**
//	 * 所属公司
//	*/
//	protected Long eid;
//	/**
//	 * 所属公司名称
//	*/
//	protected String ename;
	/**
	 * 所属部门id
	*/
	protected Long did;
	/**
	 * 所属部门名称
	*/
	protected String dname;

	//========== getters and setters ==========
    /**
     * 返回 职能
     */
	public String getFunc() {
		return func;
	}

	/**
	 * 设置 职能
     */
	public void setFunc(String func) {
		this.func = func;
    }
    /**
     * 返回 角色的级别0-1-2-3....
     */
	public Long getLevel() {
		return level;
	}

	/**
	 * 设置 角色的级别0-1-2-3....
     */
	public void setLevel(Long level) {
		this.level = level;
    }
//    /**
//     * 返回 所属公司
//     */
//	public Long getEid() {
//		return eid;
//	}
//
//	/**
//	 * 设置 所属公司
//     */
//	public void setEid(Long eid) {
//		this.eid = eid;
//    }
//    /**
//     * 返回 所属公司名称
//     */
//	public String getEname() {
//		return ename;
//	}
//
//	/**
//	 * 设置 所属公司名称
//     */
//	public void setEname(String ename) {
//		this.ename = ename;
//    }
    /**
     * 返回 所属部门id
     */
	public Long getDid() {
		return did;
	}

	/**
	 * 设置 所属部门id
     */
	public void setDid(Long did) {
		this.did = did;
    }
    /**
     * 返回 所属部门名称
     */
	public String getDname() {
		return dname;
	}

	/**
	 * 设置 所属部门名称
     */
	public void setDname(String dname) {
		this.dname = dname;
    }

}
