/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.heitian.ssm.model;


/**
 * A data object class directly models database table <tt>tb_role_action</tt>.
 * 
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tb_role_action.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
public class TbRoleActionDO  extends Entity {
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========
	/**
	 * 功能id
	*/
	protected Long aid;
	/**
	 * 功能名称
	*/
	protected String aname;
	/**
	 * 员工id
	*/
	protected Long rid;
	/**
	 *  角色名称
	*/
	protected String rname;

	//========== getters and setters ==========
    /**
     * 返回 功能id
     */
	public Long getAid() {
		return aid;
	}

	/**
	 * 设置 功能id
     */
	public void setAid(Long aid) {
		this.aid = aid;
    }
    /**
     * 返回 功能名称
     */
	public String getAname() {
		return aname;
	}

	/**
	 * 设置 功能名称
     */
	public void setAname(String aname) {
		this.aname = aname;
    }
    /**
     * 返回 员工id
     */
	public Long getRid() {
		return rid;
	}

	/**
	 * 设置 员工id
     */
	public void setRid(Long rid) {
		this.rid = rid;
    }
    /**
     * 返回  角色名称
     */
	public String getRname() {
		return rname;
	}

	/**
	 * 设置  角色名称
     */
	public void setRname(String rname) {
		this.rname = rname;
    }

}
