/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.heitian.ssm.model;

import java.util.Date;


/**
 * A data object class directly models database table <tt>tb_task</tt>.
 * 
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tb_task.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
public class TbTaskDO  extends Entity {
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========
	/**
	 * 内容
	*/
	protected String content;
	/**
	 * 完成任务人id
	*/
	protected Long eid;
	/**
	 * 完成任务人名字
	*/
	protected String ename;
	/**
	 * 开始时间
	*/
	protected Date beginTime;
	/**
	 * 完成时间
	*/
	protected Date endTime;
	/**
	 * 状态-0：未开始，1：进行中，2：结束，3：关闭
	*/
	protected Long state;

	//========== getters and setters ==========
    /**
     * 返回 内容
     */
	public String getContent() {
		return content;
	}

	/**
	 * 设置 内容
     */
	public void setContent(String content) {
		this.content = content;
    }
    /**
     * 返回 完成任务人id
     */
	public Long getEid() {
		return eid;
	}

	/**
	 * 设置 完成任务人id
     */
	public void setEid(Long eid) {
		this.eid = eid;
    }
    /**
     * 返回 完成任务人名字
     */
	public String getEname() {
		return ename;
	}

	/**
	 * 设置 完成任务人名字
     */
	public void setEname(String ename) {
		this.ename = ename;
    }
    /**
     * 返回 开始时间
     */
	public Date getBeginTime() {
		return beginTime;
	}

	/**
	 * 设置 开始时间
     */
	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
    }
    /**
     * 返回 完成时间
     */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * 设置 完成时间
     */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
    }
    /**
     * 返回 状态-0：未开始，1：进行中，2：结束，3：关闭
     */
	public Long getState() {
		return state;
	}

	/**
	 * 设置 状态-0：未开始，1：进行中，2：结束，3：关闭
     */
	public void setState(Long state) {
		this.state = state;
    }

}
