/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.heitian.ssm.dao;

//import org.springframework.stereotype.Repository;
//import org.springframework.transaction.annotation.Transactional;

import com.heitian.ssm.model.TbActionDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>tb_action</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tb_action.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
 @SuppressWarnings("rawtypes")
 @Repository
public interface TbActionMapper {
	/**
	 *  Insert one <tt>TbActionDO</tt> object to DB table <tt>tb_action</tt>, return primary key
	 *
	 * 插入数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into tb_action(id,name,url,aid,aname,remark,creator,updater,create_time,update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param tbAction
	 *	@return int
	 */	 

    public int insert(@Param("tbAction") TbActionDO tbAction);

	/**
	 *  Query DB table <tt>tb_action</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_action</tt>
	 *
	 *	@param tbAction
	 *	@param start
	 *	@param pageSize
	 *	@return List<TbActionDO>
	 */	 

    public List<TbActionDO> query(@Param("tbAction") TbActionDO tbAction, @Param("start") long start,
                                  @Param("pageSize") int pageSize);

	/**
	 *  Query DB table <tt>tb_action</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from tb_action</tt>
	 *
	 *	@param tbAction
	 *	@return long
	 */	 

    public long queryCount(@Param("tbAction") TbActionDO tbAction);

	/**
	 *  Update DB table <tt>tb_action</tt>.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update tb_action set name=? where (id = ?)</tt>
	 *
	 *	@param tbAction
	 *	@return int
	 */	 

    public int update(@Param("tbAction") TbActionDO tbAction);

	/**
	 *  Delete records from DB table <tt>tb_action</tt>.
	 *
	 * 根据主键删除数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from tb_action where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 */	 

    public int delete(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_action</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_action tbAction where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return TbActionDO
	 */	 

    public TbActionDO findById(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_action</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_action</tt>
	 *
	 *	@param idList
	 *	@return List<TbActionDO>
	 */	 

    public List<TbActionDO> findByIdIn(@Param("idList") List idList,@Param("level") Integer level);

}
