/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.heitian.ssm.dao;

//import org.springframework.stereotype.Repository;
//import org.springframework.transaction.annotation.Transactional;

import com.heitian.ssm.model.TbEmployeeRoleDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>tb_employee_role</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tb_employee_role.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
 @SuppressWarnings("rawtypes")
 @Repository
public interface TbEmployeeRoleMapper {
	/**
	 *  Insert one <tt>TbEmployeeRoleDO</tt> object to DB table <tt>tb_employee_role</tt>, return primary key
	 *
	 * 插入数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into tb_employee_role(id,eid,ename,rid,rname,remark,creator,updater,create_time,update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param tbEmployeeRole
	 *	@return int
	 */	 

    public int insert(@Param("tbEmployeeRole") TbEmployeeRoleDO tbEmployeeRole);

	/**
	 *  Query DB table <tt>tb_employee_role</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_employee_role</tt>
	 *
	 *	@param tbEmployeeRole
	 *
	 *	@return List<TbEmployeeRoleDO>
	 */	 

//    public List<TbEmployeeRoleDO> query(@Param("tbEmployeeRole") TbEmployeeRoleDO tbEmployeeRole,
//                                        @Param("start") long start, @Param("pageSize") int pageSize);
	public List<TbEmployeeRoleDO> query(@Param("tbEmployeeRole") TbEmployeeRoleDO tbEmployeeRole);
	/**
	 *  Query DB table <tt>tb_employee_role</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from tb_employee_role</tt>
	 *
	 *	@param tbEmployeeRole
	 *	@return long
	 */	 

    public long queryCount(@Param("tbEmployeeRole") TbEmployeeRoleDO tbEmployeeRole);

	/**
	 *  Update DB table <tt>tb_employee_role</tt>.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update tb_employee_role set eid=? where (id = ?)</tt>
	 *
	 *	@param tbEmployeeRole
	 *	@return int
	 */	 

    public int update(@Param("tbEmployeeRole") TbEmployeeRoleDO tbEmployeeRole);

	/**
	 *  Delete records from DB table <tt>tb_employee_role</tt>.
	 *
	 * 根据主键删除数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from tb_employee_role where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 */	 

    public int delete(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_employee_role</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_employee_role tbEmployeeRole where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return TbEmployeeRoleDO
	 */	 

    public TbEmployeeRoleDO findById(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_employee_role</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_employee_role</tt>
	 *
	 *	@param idList
	 *	@return List<TbEmployeeRoleDO>
	 */	 

    public List<TbEmployeeRoleDO> findByIdIn(@Param("idList") List idList);

}
