/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.heitian.ssm.dao;

//import org.springframework.stereotype.Repository;
//import org.springframework.transaction.annotation.Transactional;

import com.heitian.ssm.model.TbLogDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>tb_log</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tb_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
 @SuppressWarnings("rawtypes")
 @Repository
public interface TbLogMapper {
	/**
	 *  Insert one <tt>TbLogDO</tt> object to DB table <tt>tb_log</tt>, return primary key
	 *
	 * 插入数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into tb_log(id,name,content,log_number,check_user,check_username,check_time,state,remark,creator,updater,create_time,update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param tbLog
	 *	@return int
	 */	 

    public int insert(@Param("tbLog") TbLogDO tbLog);

	/**
	 *  Query DB table <tt>tb_log</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_log</tt>
	 *
	 *	@param tbLog
	 *	@param start
	 *	@param pageSize
	 *	@return List<TbLogDO>
	 */	 

    public List<TbLogDO> query(@Param("tbLog") TbLogDO tbLog, @Param("start") long start,
                               @Param("pageSize") int pageSize);

	/**
	 *  Query DB table <tt>tb_log</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from tb_log</tt>
	 *
	 *	@param tbLog
	 *	@return long
	 */	 

    public long queryCount(@Param("tbLog") TbLogDO tbLog);

	/**
	 *  Update DB table <tt>tb_log</tt>.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update tb_log set name=? where (id = ?)</tt>
	 *
	 *	@param tbLog
	 *	@return int
	 */	 

    public int update(@Param("tbLog") TbLogDO tbLog);

	/**
	 *  Delete records from DB table <tt>tb_log</tt>.
	 *
	 * 根据主键删除数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from tb_log where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 */	 

    public int delete(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_log</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_log tbLog where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return TbLogDO
	 */	 

    public TbLogDO findById(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_log</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_log</tt>
	 *
	 *	@param idList
	 *	@return List<TbLogDO>
	 */	 

    public List<TbLogDO> findByIdIn(@Param("idList") List idList);

}
