/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.heitian.ssm.dao;

//import org.springframework.stereotype.Repository;
//import org.springframework.transaction.annotation.Transactional;

import com.heitian.ssm.model.TbLoginDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>tb_login</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tb_login.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
 @SuppressWarnings("rawtypes")
 @Repository
public interface TbLoginMapper {
	/**
	 *  Insert one <tt>TbLoginDO</tt> object to DB table <tt>tb_login</tt>, return primary key
	 *
	 * 插入数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into tb_login(id,phone,password,last_login_time,last_login_address,login_number) values (?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param tbLogin
	 *	@return int
	 */	 

    public int insert(@Param("tbLogin") TbLoginDO tbLogin);

	/**
	 *  Query DB table <tt>tb_login</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_login</tt>
	 *
	 *	@param tbLogin
	 *	@param start
	 *	@param pageSize
	 *	@return List<TbLoginDO>
	 */	 

    public List<TbLoginDO> query(@Param("tbLogin") TbLoginDO tbLogin, @Param("start") long start,
                                 @Param("pageSize") int pageSize);

	/**
	 *  Query DB table <tt>tb_login</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from tb_login</tt>
	 *
	 *	@param tbLogin
	 *	@return long
	 */	 

    public long queryCount(@Param("tbLogin") TbLoginDO tbLogin);

	/**
	 *  Update DB table <tt>tb_login</tt>.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update tb_login set phone=? where (id = ?)</tt>
	 *
	 *	@param tbLogin
	 *	@return int
	 */	 

    public int update(@Param("tbLogin") TbLoginDO tbLogin);

	/**
	 *  Delete records from DB table <tt>tb_login</tt>.
	 *
	 * 根据主键删除数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from tb_login where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 */	 

    public int delete(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_login</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_login tbLogin where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return TbLoginDO
	 */	 

    public TbLoginDO findById(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_login</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_login</tt>
	 *
	 *	@param idList
	 *	@return List<TbLoginDO>
	 */	 

    public List<TbLoginDO> findByIdIn(@Param("idList") List idList);

}
