/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.heitian.ssm.dao;

//import org.springframework.stereotype.Repository;
//import org.springframework.transaction.annotation.Transactional;

import com.heitian.ssm.model.TbLookNoticeDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>tb_look_notice</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tb_look_notice.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
 @SuppressWarnings("rawtypes")
 @Repository
public interface TbLookNoticeMapper {
	/**
	 *  Insert one <tt>TbLookNoticeDO</tt> object to DB table <tt>tb_look_notice</tt>, return primary key
	 *
	 * 插入数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into tb_look_notice(id,rid,eid,ename,remark,creator,updater,create_time,update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param tbLookNotice
	 *	@return int
	 */	 

    public int insert(@Param("tbLookNotice") TbLookNoticeDO tbLookNotice);

	/**
	 *  Query DB table <tt>tb_look_notice</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_look_notice</tt>
	 *
	 *	@param tbLookNotice
	 *	@param start
	 *	@param pageSize
	 *	@return List<TbLookNoticeDO>
	 */	 

    public List<TbLookNoticeDO> query(@Param("tbLookNotice") TbLookNoticeDO tbLookNotice, @Param("start") long start,
                                      @Param("pageSize") int pageSize);

	/**
	 *  Query DB table <tt>tb_look_notice</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from tb_look_notice</tt>
	 *
	 *	@param tbLookNotice
	 *	@return long
	 */	 

    public long queryCount(@Param("tbLookNotice") TbLookNoticeDO tbLookNotice);

	/**
	 *  Update DB table <tt>tb_look_notice</tt>.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update tb_look_notice set rid=? where (id = ?)</tt>
	 *
	 *	@param tbLookNotice
	 *	@return int
	 */	 

    public int update(@Param("tbLookNotice") TbLookNoticeDO tbLookNotice);

	/**
	 *  Delete records from DB table <tt>tb_look_notice</tt>.
	 *
	 * 根据主键删除数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from tb_look_notice where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 */	 

    public int delete(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_look_notice</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_look_notice tbLookNotice where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return TbLookNoticeDO
	 */	 

    public TbLookNoticeDO findById(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_look_notice</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_look_notice</tt>
	 *
	 *	@param idList
	 *	@return List<TbLookNoticeDO>
	 */	 

    public List<TbLookNoticeDO> findByIdIn(@Param("idList") List idList);

}
