/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.heitian.ssm.dao;

//import org.springframework.stereotype.Repository;
//import org.springframework.transaction.annotation.Transactional;


import com.heitian.ssm.model.TbRepositoryDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>tb_repository</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tb_repository.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
 @SuppressWarnings("rawtypes")
 @Repository
public interface TbRepositoryMapper {
	/**
	 *  Insert one <tt>TbRepositoryDO</tt> object to DB table <tt>tb_repository</tt>, return primary key
	 *
	 * 插入数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into tb_repository(id,name,url,look_number,remark,creator,updater,create_time,update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param tbRepository
	 *	@return int
	 */	 

    public int insert(@Param("tbRepository") TbRepositoryDO tbRepository);

	/**
	 *  Query DB table <tt>tb_repository</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_repository</tt>
	 *
	 *	@param tbRepository
	 *	@param start
	 *	@param pageSize
	 *	@return List<TbRepositoryDO>
	 */	 

    public List<TbRepositoryDO> query(@Param("tbRepository") TbRepositoryDO tbRepository, @Param("start") long start,
                                      @Param("pageSize") int pageSize);

	/**
	 *  Query DB table <tt>tb_repository</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from tb_repository</tt>
	 *
	 *	@param tbRepository
	 *	@return long
	 */	 

    public long queryCount(@Param("tbRepository") TbRepositoryDO tbRepository);

	/**
	 *  Update DB table <tt>tb_repository</tt>.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update tb_repository set name=? where (id = ?)</tt>
	 *
	 *	@param tbRepository
	 *	@return int
	 */	 

    public int update(@Param("tbRepository") TbRepositoryDO tbRepository);

	/**
	 *  Delete records from DB table <tt>tb_repository</tt>.
	 *
	 * 根据主键删除数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from tb_repository where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 */	 

    public int delete(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_repository</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_repository tbRepository where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return TbRepositoryDO
	 */	 

    public TbRepositoryDO findById(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_repository</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_repository</tt>
	 *
	 *	@param idList
	 *	@return List<TbRepositoryDO>
	 */	 

    public List<TbRepositoryDO> findByIdIn(@Param("idList") List idList);

}
