/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.heitian.ssm.dao;

//import org.springframework.stereotype.Repository;
//import org.springframework.transaction.annotation.Transactional;

import com.heitian.ssm.model.TbTaskDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>tb_task</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tb_task.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
 @SuppressWarnings("rawtypes")
 @Repository
public interface TbTaskMapper {
	/**
	 *  Insert one <tt>TbTaskDO</tt> object to DB table <tt>tb_task</tt>, return primary key
	 *
	 * 插入数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into tb_task(id,name,content,eid,ename,begin_time,end_time,state,remark,creator,updater,create_time,update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param tbTask
	 *	@return int
	 */	 

    public int insert(@Param("tbTask") TbTaskDO tbTask);

	/**
	 *  Query DB table <tt>tb_task</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_task</tt>
	 *
	 *	@param tbTask
	 *	@param start
	 *	@param pageSize
	 *	@return List<TbTaskDO>
	 */	 

    public List<TbTaskDO> query(@Param("tbTask") TbTaskDO tbTask, @Param("start") long start,
                                @Param("pageSize") int pageSize);

	/**
	 *  Query DB table <tt>tb_task</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from tb_task</tt>
	 *
	 *	@param tbTask
	 *	@return long
	 */	 

    public long queryCount(@Param("tbTask") TbTaskDO tbTask);

	/**
	 *  Update DB table <tt>tb_task</tt>.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update tb_task set name=? where (id = ?)</tt>
	 *
	 *	@param tbTask
	 *	@return int
	 */	 

    public int update(@Param("tbTask") TbTaskDO tbTask);

	/**
	 *  Delete records from DB table <tt>tb_task</tt>.
	 *
	 * 根据主键删除数据
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from tb_task where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 */	 

    public int delete(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_task</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_task tbTask where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return TbTaskDO
	 */	 

    public TbTaskDO findById(@Param("id") Long id);

	/**
	 *  Query DB table <tt>tb_task</tt> for records.
	 *
	 * 
     * <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tb_task</tt>
	 *
	 *	@param idList
	 *	@return List<TbTaskDO>
	 */	 

    public List<TbTaskDO> findByIdIn(@Param("idList") List idList);

}
